version: "3.8"

services:
  webserver:
    image: phpstorm/php-71-apache-xdebug-26
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internet

# Names our volume
volumes:
  my-db: